[notes]
sw = "/Users/zach/Documents/zv/notes/sw"
domains = "/Users/zach/Documents/zv/notes/domains"
bookcase = "/Users/zach/Documents/zv/notes/bookcase"
worldview = "/Users/zach/Documents/zv/personal/worldview"

[specs]
# corkboard = "/Users/zach/Documents/zv/projects/tools/corkboard"
tasks = "/Users/zach/Documents/zv/personal/corkboard-tasks"
rdd = "/Users/zach/Documents/zv/projects/data/rdd"

[denv]
dot = "/Users/zach/Documents/denv/dotfiles"
worklogs = "/Users/zach/Documents/zv/personal/worklogs"
# bin = "/Users/zach/Documents/denv/bin"
# logs = "/Users/zach/Documents/denv/logs"

[colligo]
# org = "/Users/zach/Documents/zv/work/colligo/docs/org"
# eng = "/Users/zach/Documents/zv/work/colligo/docs/eng"
worklogs = "/Users/zach/Documents/zv/work/colligo/docs/worklogs"
